import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { type, theme, duration, voiceType } = body

    // Validar parâmetros obrigatórios
    if (!type || !theme) {
      return NextResponse.json(
        { error: 'Parâmetros obrigatórios: type e theme' },
        { status: 400 }
      )
    }

    // Simular delay de processamento
    await new Promise(resolve => setTimeout(resolve, 1000))

    // Conteúdo gerado baseado nos parâmetros
    const generateContent = (type: string, theme: string, duration: number = 15, voiceType: string = 'female') => {
      const templates = {
        sleep: {
          female: [
            `Feche os olhos suavemente... respire fundo... imagine-se em ${theme.toLowerCase()}... 
            Cada respiração te leva mais fundo no relaxamento... seus músculos se soltam completamente...
            O mundo ao seu redor desaparece... você está seguro e tranquilo... 
            Deixe sua mente flutuar como uma nuvem no céu... sem pressa, sem preocupações...
            Agora, permita-se mergulhar no sono mais reparador...`,
            
            `Você está em um lugar especial... ${theme.toLowerCase()}... onde a paz reina absoluta...
            Sinta a tranquilidade envolvendo todo seu ser... cada músculo relaxando profundamente...
            Sua respiração fica mais lenta e suave... seu coração bate em ritmo calmo...
            Deixe todos os pensamentos do dia se dissolverem... como folhas levadas pelo vento...
            Agora é hora de descansar... de se entregar ao sono profundo e reparador...`
          ],
          male: [
            `Respire profundamente... sinta seu corpo pesado e relaxado... você está em ${theme.toLowerCase()}...
            Cada expiração libera toda a tensão do dia... seus músculos se soltam completamente...
            Sua mente fica clara e tranquila... sem pensamentos perturbadores...
            Você está seguro e protegido... pode se entregar completamente ao descanso...
            Deixe o sono vir naturalmente... profundo e reparador...`,
            
            `Imagine-se em ${theme.toLowerCase()}... um lugar de paz absoluta...
            Sinta o peso do seu corpo afundando no colchão... completamente relaxado...
            Sua respiração fica automática e suave... seu coração bate calmamente...
            Todos os problemas ficam para amanhã... agora é só descanso...
            Permita-se dormir profundamente... seu corpo e mente merecem esse descanso...`
          ]
        },
        breathing: {
          female: [
            `Vamos começar nossa jornada de respiração consciente... inspire pelo nariz por 4 segundos...
            Segure o ar por 7 segundos... sinta o oxigênio nutrindo cada célula...
            Agora expire pela boca por 8 segundos... liberando toda a tensão...
            Continue esse ritmo... 4... 7... 8... sentindo seu corpo relaxar a cada ciclo...
            Sua mente fica mais clara... seu coração mais calmo... você está no controle...`,
            
            `Coloque uma mão no peito e outra na barriga... vamos respirar juntas...
            Inspire lentamente pelo nariz... sinta sua barriga se expandir...
            Expire suavemente pela boca... deixando todo o estresse sair...
            A cada respiração você fica mais centrada... mais presente... mais em paz...
            Continue respirando conscientemente... encontrando seu ritmo natural...`
          ],
          male: [
            `Vamos praticar a respiração que acalma o sistema nervoso... inspire profundamente...
            Conte até 4 na inspiração... segure por 7... expire por 8...
            Sinta seu corpo respondendo a cada respiração... relaxando profundamente...
            Sua mente fica mais focada... seus músculos se soltam...
            Continue esse padrão... deixando a respiração te guiar para a calma...`,
            
            `Respire comigo... inspire pelo nariz... expire pela boca...
            Sinta o ar entrando e saindo... nutrindo seu corpo... acalmando sua mente...
            A cada expiração você libera a tensão... a cada inspiração você recebe paz...
            Sua respiração é sua âncora... te mantém presente e centrado...
            Continue respirando conscientemente... encontrando sua paz interior...`
          ]
        },
        meditation: {
          female: [
            `Bem-vinda a este momento de meditação... sente-se confortavelmente...
            Feche os olhos e volte sua atenção para dentro... para seu centro...
            Observe seus pensamentos sem julgamento... deixe-os passar como nuvens...
            Conecte-se com a paz que existe naturalmente dentro de você...
            Você é mais do que seus pensamentos... você é a consciência que os observa...
            Permaneça neste estado de presença pura... de paz profunda...`,
            
            `Neste momento você está exatamente onde precisa estar... respire suavemente...
            Sinta a conexão com seu eu mais profundo... com sua essência...
            Deixe qualquer tensão se dissolver... qualquer preocupação se afastar...
            Você é um ser de luz e amor... conectada com toda a existência...
            Permaneça nesta consciência expandida... nesta paz infinita...`
          ],
          male: [
            `Encontre uma posição confortável... feche os olhos... respire naturalmente...
            Observe sua respiração sem tentar mudá-la... apenas observe...
            Quando pensamentos surgirem, reconheça-os e deixe-os passar...
            Você está cultivando a habilidade de estar presente... de estar em paz...
            Sua mente fica mais clara... seu coração mais aberto...
            Continue nesta prática... encontrando sua paz interior...`,
            
            `Bem-vindo a este espaço sagrado de meditação... respire profundamente...
            Sinta-se conectado com o momento presente... com sua respiração...
            Deixe sua mente se aquietar... como um lago que fica calmo...
            Você é o observador silencioso... a consciência pura...
            Permaneça neste estado de presença... de paz profunda...`
          ]
        },
        relaxation: {
          female: [
            `É hora de relaxar completamente... deixe seu corpo afundar...
            Comece pelos pés... sinta-os relaxando... subindo pelas pernas...
            Seus músculos se soltam um por um... como se derretessem...
            Seus ombros caem... seu rosto se suaviza... sua mente se acalma...
            Você está em um estado de relaxamento profundo... segura e tranquila...
            Permita-se ficar neste estado... sem pressa... sem preocupações...`,
            
            `Imagine-se em um lugar de paz absoluta... onde nada pode te perturbar...
            Sinta uma onda de relaxamento percorrendo todo seu corpo...
            Cada músculo se solta... cada tensão se dissolve...
            Sua respiração fica suave e natural... seu coração bate calmamente...
            Você está completamente relaxada... em harmonia consigo mesma...`
          ],
          male: [
            `Deixe todo o peso do dia sair dos seus ombros... respire fundo...
            Sinta seu corpo pesado e relaxado... afundando no conforto...
            Cada músculo se solta... cada tensão se dissolve...
            Sua mente fica clara e tranquila... livre de preocupações...
            Você está em um estado de relaxamento profundo... seguro e em paz...
            Permaneça neste estado... deixando o relaxamento te envolver...`,
            
            `Agora é seu momento de descanso... de se desconectar do mundo...
            Sinta uma sensação de alívio percorrendo todo seu corpo...
            Seus músculos relaxam completamente... sua mente se aquieta...
            Você está em um lugar seguro... onde pode se entregar ao relaxamento...
            Continue respirando suavemente... deixando a paz te envolver...`
          ]
        }
      }

      const categoryTemplates = templates[type as keyof typeof templates]
      if (!categoryTemplates) {
        throw new Error(`Categoria inválida: ${type}`)
      }

      const voiceTemplates = categoryTemplates[voiceType as keyof typeof categoryTemplates]
      if (!voiceTemplates) {
        throw new Error(`Tipo de voz inválido: ${voiceType}`)
      }

      const selectedTemplate = voiceTemplates[Math.floor(Math.random() * voiceTemplates.length)]

      return {
        title: `${theme} - ${type === 'sleep' ? 'História para Dormir' : 
                           type === 'breathing' ? 'Respiração Guiada' :
                           type === 'meditation' ? 'Meditação' : 'Relaxamento'}`,
        content: selectedTemplate,
        duration: `${duration} min`,
        category: type,
        voiceType
      }
    }

    const content = generateContent(type, theme, duration || 15, voiceType || 'female')

    return NextResponse.json(content, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })

  } catch (error: any) {
    console.error('Erro ao gerar conteúdo:', error)
    return NextResponse.json(
      { 
        error: 'Erro interno do servidor',
        message: error.message || 'Erro desconhecido'
      },
      { status: 500 }
    )
  }
}